//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_App.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddressType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAddressType()
        {
            this.tblRelationAddress = new HashSet<tblRelationAddress>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code1 { get; set; }
        public string Code2 { get; set; }
        public string Code3 { get; set; }
        public string Code4 { get; set; }
        public string Code5 { get; set; }
        public string Code6 { get; set; }
        public Nullable<double> Value1 { get; set; }
        public Nullable<double> Value2 { get; set; }
        public Nullable<double> Value3 { get; set; }
        public Nullable<double> Value4 { get; set; }
        public Nullable<bool> Flag1 { get; set; }
        public Nullable<bool> Flag2 { get; set; }
        public Nullable<bool> Flag3 { get; set; }
        public Nullable<bool> Flag4 { get; set; }
        public Nullable<System.DateTime> Timestamp1 { get; set; }
        public Nullable<System.DateTime> Timestamp2 { get; set; }
        public Nullable<System.DateTime> Timestamp3 { get; set; }
        public Nullable<System.DateTime> Timestamp4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRelationAddress> tblRelationAddress { get; set; }
    }
}
