//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_App.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRelationCategory
    {
        public System.Guid RelationId { get; set; }
        public System.Guid CategoryId { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblRelation tblRelation { get; set; }
    }
}
