//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_App.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRelation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRelation()
        {
            this.tblRelationAddress = new HashSet<tblRelationAddress>();
            this.tblRelationCategory = new HashSet<tblRelationCategory>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<System.Guid> ParentRelationId { get; set; }
        public bool IsTemporary { get; set; }
        public bool IsMe { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string DepartureName { get; set; }
        public string ArrivalName { get; set; }
        public string DefaultStreet { get; set; }
        public string DefaultPostalCode { get; set; }
        public string DefaultCity { get; set; }
        public string DefaultCountry { get; set; }
        public string EMailAddress { get; set; }
        public string Url { get; set; }
        public string IMAddress { get; set; }
        public string SkypeAddress { get; set; }
        public string TelephoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string FaxNumber { get; set; }
        public string EmergencyNumber { get; set; }
        public Nullable<System.DateTime> DepartureBetween { get; set; }
        public Nullable<System.DateTime> DepartureBetweenAnd { get; set; }
        public Nullable<System.DateTime> ArrivalBetween { get; set; }
        public Nullable<System.DateTime> ArrivalBetweenAnd { get; set; }
        public string Remarks { get; set; }
        public string CustomerCode { get; set; }
        public string DebtorNumber { get; set; }
        public string VendorNumber { get; set; }
        public string InvoiceTo { get; set; }
        public string InvoiceEMailAddress { get; set; }
        public Nullable<bool> SendInvoiceDigital { get; set; }
        public Nullable<System.Guid> VatId { get; set; }
        public string VatName { get; set; }
        public Nullable<double> PaymentTerm { get; set; }
        public bool PaymentViaAutomaticDebit { get; set; }
        public string VatNumber { get; set; }
        public string ChamberOfCommerce { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string BankBic { get; set; }
        public Nullable<double> CalculateMinimalPrice { get; set; }
        public Nullable<bool> CalculatePriceManually { get; set; }
        public Nullable<bool> CalculatePriceByPriceList { get; set; }
        public Nullable<System.Guid> PriceListId { get; set; }
        public string PriceListName { get; set; }
        public Nullable<bool> CalculatePriceBasedOnPositions { get; set; }
        public Nullable<bool> CalculatePriceBasedOnAmount { get; set; }
        public Nullable<bool> CalculatePriceBasedOnWeight { get; set; }
        public Nullable<bool> CalculatePriceBasedOnDistance { get; set; }
        public Nullable<bool> CalculatePriceBasedOnTonne { get; set; }
        public Nullable<bool> CalculatePriceByFixed { get; set; }
        public Nullable<bool> CalculatePriceByDistance { get; set; }
        public Nullable<bool> CalculatePriceBasedOnEpq { get; set; }
        public Nullable<bool> CalculatePriceBasedOnLoadingMeters { get; set; }
        public Nullable<bool> CalculatePriceBasedOnVolume { get; set; }
        public Nullable<double> CalculatePriceByFixedPrice { get; set; }
        public Nullable<double> CalculateMinimalPriceForCollecting { get; set; }
        public Nullable<bool> CalculatePriceManuallyForCollecting { get; set; }
        public Nullable<bool> CalculatePriceByPriceListForCollecting { get; set; }
        public Nullable<System.Guid> PriceListIdForCollecting { get; set; }
        public string PriceListNameForCollecting { get; set; }
        public Nullable<bool> CalculatePriceBasedOnPositionsForCollecting { get; set; }
        public Nullable<bool> CalculatePriceBasedOnAmountForCollecting { get; set; }
        public Nullable<bool> CalculatePriceBasedOnWeightForCollecting { get; set; }
        public Nullable<bool> CalculatePriceBasedOnDistanceForCollecting { get; set; }
        public Nullable<bool> CalculatePriceBasedOnTonneForCollecting { get; set; }
        public Nullable<bool> CalculatePriceByFixedForCollecting { get; set; }
        public Nullable<bool> CalculatePriceByDistanceForCollecting { get; set; }
        public Nullable<bool> CalculatePriceBasedOnEpqForCollecting { get; set; }
        public Nullable<bool> CalculatePriceBasedOnLoadingMetersForCollecting { get; set; }
        public Nullable<bool> CalculatePriceBasedOnVolumeForCollecting { get; set; }
        public Nullable<double> CalculatePriceByFixedPriceForCollecting { get; set; }
        public string GeographicalRegions { get; set; }
        public Nullable<bool> SendDigitalFreightDocumentsByEMail { get; set; }
        public Nullable<System.Guid> DigitalFreightDocumentEMailTemplateId { get; set; }
        public Nullable<bool> SendFreightStatusUpdateByEMail { get; set; }
        public Nullable<bool> DepartureTimeSlotsAreAllEqual { get; set; }
        public Nullable<System.Guid> DepartureTimeSlotIdOnSundays { get; set; }
        public Nullable<System.Guid> DepartureTimeSlotIdOnMondays { get; set; }
        public Nullable<System.Guid> DepartureTimeSlotIdOnTuesdays { get; set; }
        public Nullable<System.Guid> DepartureTimeSlotIdOnWednesdays { get; set; }
        public Nullable<System.Guid> DepartureTimeSlotIdOnThursdays { get; set; }
        public Nullable<System.Guid> DepartureTimeSlotIdOnFridays { get; set; }
        public Nullable<System.Guid> DepartureTimeSlotIdOnSaturdays { get; set; }
        public Nullable<bool> ArrivalTimeSlotsAreAllEqual { get; set; }
        public Nullable<System.Guid> ArrivalTimeSlotIdOnSundays { get; set; }
        public Nullable<System.Guid> ArrivalTimeSlotIdOnMondays { get; set; }
        public Nullable<System.Guid> ArrivalTimeSlotIdOnTuesdays { get; set; }
        public Nullable<System.Guid> ArrivalTimeSlotIdOnWednesdays { get; set; }
        public Nullable<System.Guid> ArrivalTimeSlotIdOnThursdays { get; set; }
        public Nullable<System.Guid> ArrivalTimeSlotIdOnFridays { get; set; }
        public Nullable<System.Guid> ArrivalTimeSlotIdOnSaturdays { get; set; }
        public int InvoiceDateGenerationOptions { get; set; }
        public int InvoiceGroupByOptions { get; set; }
        public string InvoiceGroupByTransportOrderColumnName { get; set; }
        public string GeneralLedgerAccount { get; set; }
        public Nullable<System.Guid> TransportUnitTransactionOverviewTextTemplateId { get; set; }
        public Nullable<bool> SendFreightDocumentsAlongWithInvoice { get; set; }
        public string CarrierCode { get; set; }
        public string SupplyNumber { get; set; }
        public Nullable<System.Guid> ThirdPartyToUseForInvoicing { get; set; }
        public Nullable<int> Flags { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRelationAddress> tblRelationAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRelationCategory> tblRelationCategory { get; set; }
    }
}
