//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_App.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRelationAddress
    {
        public System.Guid RelationId { get; set; }
        public System.Guid AddressTypeId { get; set; }
        public string Street { get; set; }
        public Nullable<int> Number { get; set; }
        public string NumberSuffix { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Building { get; set; }
        public string PostalCode { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public string CountryName { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual tblAddressType tblAddressType { get; set; }
        public virtual tblCountry tblCountry { get; set; }
        public virtual tblRelation tblRelation { get; set; }
    }
}
